- src/GurobiSolverInterface.jl
- src/grb_callbacks.jl
Also fixes a typo in callback code.
> Add support for informational callbacks

- src/Gurobi.jl
- src/grb_model.jl
Interface for the fixedmodel function in Gurobi.
http://www.gurobi.com/documentation/6.0/refman/grbfixedmodel.html
> Implement fixedmodel interface

- src/GurobiSolverInterface.jl
see https://github.com/JuliaOpt/JuMP.jl/pull/422
> implement getsolvetime for MathProgBase

- src/GurobiSolverInterface.jl
> implement getnodecount

- deps/build.jl
Same as https://github.com/JuliaLang/julia/commit/123e18a07c77b7576e8d2645d7c8797056f092a0
> fix windows v0.4- install problem

- src/GurobiSolverInterface.jl
This stores the constraint bounds in the ``GurobiMathProgModel`` and updates them whenever ``update model!`` is called. This allows us to switch equality constraints to inequality constraints (@semartin). The previous behavior didn't follow the MPB spec, since calling ``setconstrLB!(...)`` would change the right-hand side of an equality constraint, rather than only changing the lower bound.
> [RFC] More consistent handling for constraint bounds

- src/GurobiSolverInterface.jl
- src/grb_model.jl
Ref https://groups.google.com/forum/#!topic/julia-opt/BJ37w-EgmBA
> terminate instead of throwing error when user exits from callback

- REQUIRE
- src/Gurobi.jl
- src/GurobiSolverInterface.jl
- src/grb_attrs.jl
- src/grb_callbacks.jl
- src/grb_common.jl
- src/grb_env.jl
- src/grb_highlevel.jl
- src/grb_model.jl
- src/grb_params.jl
- src/grb_solve.jl
@tkelman, does this seem reasonable?
> deprecation fixes for Julia 0.5

- src/GurobiSolverInterface.jl
ref: https://github.com/JuliaOpt/JuMP.jl/pull/814
> Fire info callbacks in all states and maintain state information

- deps/build.jl
> fix deprecation warnings in build.jl with v0.5.0

- deps/build.jl
Adds support for the upcoming release of Gurobi 7.0.
> Add support for Gurobi 7.0

- src/GurobiSolverInterface.jl
- test/mathprog.jl
> implement solver-independent parameters

- src/grb_callbacks.jl
https://www.gurobi.com/documentation/7.0/refman/c_grbcbsolution.html
CC @chriscoey
> update for Gurobi API change

- src/grb_common.jl
related to #90, #71 and this [topic](https://discourse.julialang.org/t/macro-that-uses-ccall-in-julia-0-6-0/2639)
> Fix gurobi on win64 and julia-0.6.0-alpha

- test/env.jl
- test/lp_01a.jl
- test/lp_01b.jl
- test/lp_02.jl
- test/lp_03.jl
- test/lp_04.jl
- test/mip_01.jl
- test/qcqp_01.jl
- test/qp_01.jl
- test/qp_02.jl
- test/range_constraints.jl
- test/test_get_strarray.jl
- test/test_grb_attrs.jl
Tests pass on my local machine
> Change to testsets

- src/GurobiSolverInterface.jl
Ref https://github.com/JuliaOpt/Gurobi.jl/issues/60#issuecomment-293706516
> Change to objective bug error to warning and only on <v7

- src/grb_attrs.jl
- src/grb_common.jl
- src/grb_constrs.jl
- src/grb_solve.jl
Needed updates for MathOptInterfaceGurobi.jl
> MOI compatibility

- src/GurobiSolverInterface.jl
- test/multiobj.jl
- test/runtests.jl
> Add support for hierarchical multi-objectives

- src/MOIWrapper.jl
As suggested by @tkoolen https://github.com/JuliaOpt/Gurobi.jl/pull/125#discussion_r203478342
> Fix handling of duplicate terms in objective

- src/grb_constrs.jl
- test/runtests.jl
> fix assertion in get_constrs

- src/MOIWrapper.jl
- test/MOIWrapper.jl
> return primal feasible when possible, even when user limits are reached

- src/MOIWrapper.jl
- test/MOIWrapper.jl
Requires https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/39
> concretely type the inner model

- REQUIRE
- deps/build.jl
> fix a few 0.7 deprecations

- REQUIRE
- src/MOIWrapper.jl
- test/MOIWrapper.jl
Updates to support MOI 0.6. Tests passing on OSX for Julia 0.6, 0.7 and 1.0.
> updates to MOI 06

- src/MPBWrapper.jl
Closes #159 
I'm not able to test this. @chriscoey, @CBongiova please confirm that this fixes the issue.
> Fix broken MPB callback interface

- deps/build.jl
> Add support for Gurobi 8.1

- deps/build.jl
Closes #169 
I haven't tested this because I don't have a mac, but @wgthompson [said that it worked](https://github.com/JuliaOpt/Gurobi.jl/issues/169#issuecomment-438106640).
> Check for `.dylib` on OSX

- REQUIRE
- src/MOIWrapper.jl
- test/MOIWrapper.jl
> DNMY: update LQOI

- REQUIRE
- src/MOIWrapper.jl
- test/MOIWrapper.jl
> DNMY: Update to LQOI 0.6

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Restores the functionality that existed in MPB: https://github.com/JuliaOpt/Gurobi.jl/pull/57
> Allow passing Env to Optimizer

- deps/build.jl
> Escape GUROBI_HOME path on windows

- src/MOI_wrapper.jl
@ExpandingMan can you check that this fixes https://github.com/JuliaOpt/Gurobi.jl/issues/195#issuecomment-465378059
> Cache number of constraints to avoid unnecessary updates

- src/MOI_wrapper.jl
cc @ExpandingMan 
Can you check if this fixes #195 (and maybe provide a test-case?).
> Fix missing update

- README.md
> Expand installation instructions in README

- README.md
I forgot some the first time around!
> Fix instances of old JuMP API

- .gitignore
- Project.toml
- REQUIRE
- deps/build.jl
- src/Gurobi.jl
- src/MOI_wrapper.jl
- src/MPB_wrapper.jl
- src/grb_common.jl
- src/grb_constrs.jl
- src/grb_quad.jl
- test/C/lp_01a.jl
- test/C/lp_01b.jl
- test/C/lp_02.jl
- test/C/lp_03.jl
- test/C/lp_04.jl
- test/C/mip_01.jl
- test/C/multiobj.jl
- test/C/qcqp_01.jl
- test/C/qp_01.jl
- test/C/qp_02.jl
- test/C/test_get_strarray.jl
- test/C/test_grb_attrs.jl
- test/C/test_read.jl
- test/MOI_wrapper.jl
- test/MathProgBase/env.jl
- test/MathProgBase/large_coefficients.jl
- test/MathProgBase/mathprog.jl
- test/MathProgBase/range_constraints.jl
- test/c_wrapper.jl
- test/runtests.jl
> Update Julia to Julia 1.0

- src/MOI_wrapper.jl
See https://github.com/JuliaOpt/MathOptInterface.jl/blob/6ac4e6d6ee47486062ab9a14816aca6d51328760/src/attributes.jl#L157-L159
> Remove supports for non-copyable attributes

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
MOI setters and getters for constraint attributes, as discussed here: https://github.com/JuliaOpt/Gurobi.jl/issues/211
> MOI.set() and MOI.get() for constraint attributes

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
MOI support for setting and getting variable attributes. This is similar to what has been done for constraint attributes in https://github.com/JuliaOpt/Gurobi.jl/pull/243
> MOI.get() and MOI.set() for variable attributes

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> MOI.get() and MOI.set() for model attributes

- README.md
A follow-up to the recent work by @fa-bien on Gurobi-specific attributes.
Closes #246
Closes #211
> Discuss Gurobi-specific attributes

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Any ideas for how to test this in a numerically stable way?
Closes #250
> Use tolerance for SingleVariable dual checks

- src/MOI_wrapper.jl
- src/grb_common.jl
- test/MOI_wrapper.jl
> Handle GRB_UNDEFINED start values

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Fixes for handling ObjectiveFunctionType

- deps/build.jl
One-line edit to (hopefully) support Gurobi 9.0.0
https://github.com/JuliaOpt/Gurobi.jl/issues/272
> Update build.jl to support Gurobi 9.0.0

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes #262
@LefterisM, I cherry-picked your commit from #262.
> Fix types of attribute queries and add tests

- src/grb_params.jl
> Added WorkerPool to parameter list

- src/MOI_callbacks.jl
- test/MOI_callbacks.jl
As suggested by @mlubin: https://github.com/JuliaOpt/JuMP.jl/issues/2123#issuecomment-569446512
> Set LazyConstraints by default

- Project.toml
- src/MOI_callbacks.jl
- test/MOI_callbacks.jl
> Add missing supports for Callbacks

- src/grb_params.jl
> Add NonConvex parameter 

- Project.toml
- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Revert QCPDual to default

- README.md
I also updated some outdated links.
> remove deprecated code from Gurobi README

- README.md
Modified 1.1, 1.3, and 1.4 to match problem formulation. 
x and y constraints switched, x + y now maximized.
> Updated readme example 1

- src/MOI_wrapper.jl
- test/MOI/MOI_callbacks.jl
- test/MOI/MOI_multiobjective.jl
- test/MOI/MOI_wrapper.jl
- test/runtests.jl
I have a local fix for #336, but it required some initial refactoring, so I'll split the PR into two parts.
> Refactor tests into functions

- test/MOI/MOI_callbacks.jl
- test/MOI/MOI_multiobjective.jl
- test/MOI/MOI_wrapper.jl
- test/runtests.jl
Closes #336 
@ccoffrin want to test?
> Refactor tests to pass with limited licenses

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Support MOI.NumberOfThreads

- Project.toml
- README.md
- src/deprecated_functions.jl
> Remove exports of copy and read, and update documentation

- src/deprecated_functions.jl
Not sure why this didn't get included in the file automatically.
> Deprecate GurobiSolver

- Project.toml
- src/MOI_callbacks.jl
- test/MOI/MOI_callbacks.jl
> Support MOI.CallbackNodeStatus

- README.md
Closes https://github.com/jump-dev/Gurobi.jl/issues/381
> [README] Explain how to use GRBterminate

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
I have encountered performance issues in my code when a lot of SOS constraints are deleted from the model, so I add batch deletion of SOS constraints (based on existing batch deletion of affine constraints) and accompanying test.
> Add batch delete for SOS constraints and related test.

- src/MOI_callbacks.jl
- test/MOI/MOI_callbacks.jl
x-ref https://github.com/jump-dev/CPLEX.jl/pull/354
> Allow broadcasting in callbacks

- src/MOI_wrapper.jl
I did a PR long ago to add comments to these arcane tricks I wrote. This one escaped me. I tried to add it to #398 but it was (rightfully) considered off-topic. Solving this now.
> Commenting arcane trick in column deletion.

- deps/build.jl
Closes #400 
We should look for newer versions first.
cc @niclasmattsson
> Look for 91 before 90

- Project.toml
- src/MOI_wrapper.jl
Motivated by this thread: https://discourse.julialang.org/t/jump-optimize-call-will-very-rarely-violate-models-time-limit-parameters-by-huge-factors/58061/17
cc @Antelling
> Allow enable_interrupts=false

- test/MOI/MOI_wrapper.jl
Haven't tested locally, but now we have CI...
> Update list of failing tests

- src/MOI_wrapper/MOI_wrapper.jl
> Fix NodeCount

- src/MOI_wrapper/MOI_wrapper.jl
Fix #446
@niclasmattsson can you test your example on this PR?
> Fix performance with quadratic constraints

- deps/build.jl
- src/Gurobi.jl
Closes #438
@ExpandingMan can you test this branch please?
> Always write deps.jl so Gurobi.jl is recompiled on Pkg.build

- Project.toml
Releasing v1.0 seems premature. So I'm going to release v0.11 that is compatible with MOI v1.
> Revert version to v0.11

- README.md
> Update RawParameter to RawOptimizerAttribute

- deps/build.jl
- perf/perf.jl
- scripts/clang.jl
- src/Gurobi.jl
- src/MOI_wrapper/MOI_callbacks.jl
- src/MOI_wrapper/MOI_indicator_constraint.jl
- src/MOI_wrapper/MOI_multi_objective.jl
- src/MOI_wrapper/MOI_wrapper.jl
- src/gen90/libgrb_api.jl
- src/gen90/libgrb_common.jl
- src/gen91/libgrb_api.jl
- src/gen91/libgrb_common.jl
- src/gen95/libgrb_api.jl
- src/gen95/libgrb_common.jl
- test/MOI/MOI_callbacks.jl
- test/MOI/MOI_multiobjective.jl
- test/MOI/MOI_wrapper.jl
- test/runtests.jl
See also https://github.com/jump-dev/CPLEX.jl/pull/401
> Add license headers

- deps/build.jl
- src/Gurobi.jl
Closes #468
@nickrobinson251 can you test this branch please?
> Fix JL_SKIP_LIB_CHECK installation

- src/MOI_wrapper/MOI_wrapper.jl
This is technically a bug-fix, because MOI 1.0 removed support for ConstraintName on VariableIndex.
> Remove support for ConstraintName on VariableIndex

- README.md
> Adding documentation about Gurobi Error 1009.

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Fix is_set_by_optimize for Gurobi-specific attributes

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Fix DualStatus when QCPDual fails due to numerics

- src/MOI_wrapper/MOI_multi_objective.jl
- test/MOI/MOI_wrapper.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2150
> Fix changing the number of multiple objectives

- README.md
Discussed this with @simonbowly @stevedwards and @VaYf
> Update affiliation in README.md

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Closes https://github.com/jump-dev/Gurobi.jl/issues/522
> First constraint index to 1 instead of 2

- src/MOI_wrapper/MOI_wrapper.jl
Ref: https://www.gurobi.com/documentation/10.0/refman/optimization_status_codes.html
Add the last two status codes.
> Add new status code

- Project.toml
This release adds support for Gurobi 11
> Prep for v1.2.0

- README.md
x-ref https://github.com/jump-dev/MathOptInterface.jl/issues/2361#issuecomment-1857176018
> Fix example of Gurobi-specific attributes from JuMP in README.md

- README.md
x-ref https://github.com/jump-dev/JuMP.jl/issues/3701
> Add Indicator constraints to README

- Project.toml
Someone else hit `SUBOPTIMAL` on discourse, so we should tag a new release: https://discourse.julialang.org/t/locally-solved-status-with-gurobi/111539
> Prep for v1.2.2

- README.md
To match https://github.com/jump-dev/CPLEX.jl/pull/448
> Add Getting help section to README

- Project.toml
I'm tempted to just silently release this and see if anyone notices or posts an issue.
> Prep for v1.3.0

- README.md
> Update manual install instructions in README

- README.md
> Clarify license instructions in README

- .codecov.yml
- deps/build.jl
- scripts/gen.jl
- scripts/generate.toml
- src/Gurobi.jl
- src/gen120/libgrb_api.jl
https://github.com/jump-dev/Gurobi.jl/pull/575#issuecomment-2445097604
> Add v12 interface

- Project.toml
Doesn't include the nonlinear stuff. That can go in a separate release just by itself.
> Prep for v1.4.0

- src/Gurobi.jl
> Add a more informative error if deps.jl is not found

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Closes https://github.com/jump-dev/Gurobi.jl/issues/602
> Add support for ConstraintConflictStatus with SOS constraints

- README.md
The correction is: ssolver -> solver
> Correct small typo in README.md

- Project.toml
- src/Gurobi.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2643
> Add PrecompileTools.jl

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
x-ref https://github.com/jump-dev/JuMP.jl/issues/3948
> Add support for MOI.write_to_file

- README.md
x-ref https://github.com/jump-dev/JuMP.jl/issues/3948
> Explain how to generate an MPS file in the README

- src/Gurobi.jl
- test/MOI/MOI_wrapper.jl
> Precompile only if Env() succeeds

- src/MOI_wrapper/MOI_multi_objective.jl
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Fix check for NumVars when there is a ScalarNonlinearFunction

- README.md
x-ref https://github.com/odow/SDDP.jl/issues/859
> Clarify that Gurobi.Env are not thread safe

- README.md
> Remove old link from README
