- src/Gurobi.jl
this allows installing in a non-default location
> Use relative path for deps.jl check

- src/GurobiSolverInterface.jl
This answer on Gurobi Google Groups (https://groups.google.com/forum/#!topic/gurobi/8JiUTt7CcMg) suggests that Gurobi 'Slack' variables are signed based on the 'Sense' attribute of the constraint. This may have led to a small sign error in getconstrsolution which I attempted to fix. I hope this works :)
> Small update to fix issue #40

- deps/build.jl
Gurobi 5.5 was released 2.5 years ago, so I think we can drop support for the previous version.
> drop support for gurobi 5.1

- src/GurobiSolverInterface.jl
Ref https://github.com/JuliaOpt/JuMP.jl/issues/779
I'm thinking this should be a warning at the solver level instead of at the JuMP level, since Gurobi is the one silently ignoring the callbacks.
CC @leethargo @fserra
> warn when using callbacks outside of MIP

- README.md
- src/GurobiSolverInterface.jl
- test/env.jl
- test/runtests.jl
This adds the option of passing a pre-existing `Gurobi.Env` as the first arg to `GurobiSolver`. Previously `env` would be created every time the `GurobiMathProgModel` was created, which was causing issues when using Gurobi with floating-use licences if models were being created at a very fast rate. This option allows you to use the recommended setup of a single env for multiple models to get around this ([ref](http://www.gurobi.com/documentation/6.5/refman/c_grbloadenv.html))
The only other change needed is to make sure that `finalize_env` is always false if the user supplied the `env`.
I can confirm that these changes have fixed the issues I was having, and that the tests are passing for me locally modulo #47. Do we need an explicit test for this and if so what should it test?
@mlubin
> Allow passing env to GurobiSolver

- src/GurobiSolverInterface.jl
- test/reformulation_bug.jl
See https://github.com/JuliaOpt/Gurobi.jl/issues/60
The alternative is catching this at the C interface level. However I went this (quick) route first because I presume/hope no one is using Gurobi.jl by itself. Going the C route would involve catching the setAttr functions that can be used to modify the objective as well as the add variable functions.
This bug has existed since the very first version of Gurobi. Some sort of catch definitely needs to go in. Gurobi ends up solving a different problem to the one you specify so without it we really have no idea of the frequency of this occurrence.
@mlubin
> Add catch for objective bug through MPB layer

- src/grb_quad.jl
https://github.com/JuliaOpt/JuMP.jl/issues/877
CC @rb004f
> shouldn't ignore empty quadratic constraints if there's a linear part

- src/GurobiSolverInterface.jl
- test/range_constraints.jl
- test/reformulation_bug.jl
- test/runtests.jl
The reformulation bug (https://github.com/JuliaOpt/Gurobi.jl/issues/60) error message was being triggered by the additional slack variables introduced by range constraints.
Tests pass on my local machine.
> Stop reformulation bug error triggering on range constraints

- src/grb_callbacks.jl
- src/grb_constrs.jl
- src/grb_quad.jl
- src/grb_vars.jl
``Int32[1,2,3] .- 1`` will now promote the answer to an ``Int64`` array which means that junk was being fed into the C calls.
CC @joehuchette, likely also relevant to cplex.
> fix for promotion changes in 0.6

- src/GurobiSolverInterface.jl
When `loadproblem!` is called with a file, `lb`, `ub` and `obj` do not correspond to the internal value of Gurobi. This PR fixes this by setting them to nothing to show that they do not represent the internal value and set them to the internal value when needed.
> Fix loadproblem! from file

- src/GurobiSolverInterface.jl
- src/grb_solve.jl
This pull request adds a couple status codes that are documented [here](https://www.gurobi.com/documentation/7.0/refman/optimization_status_codes.html). The last status code seems to be required to use the [BestObjStop](http://www.gurobi.com/documentation/7.0/refman/bestobjstop.html#parameter:BestObjStop) option like `Gurobi.GurobiSolver(BestObjStop=...)`.
> add more status codes

- src/GurobiSolverInterface.jl
The error which asks users to comment on #60 has a period immediately after the url, which results in the url being parsed as `https://github.com/JuliaOpt/Gurobi.jl/issues/60.` when displayed in, for example, IJulia. This makes it look like the issue has been removed, and might be preventing users from reporting occurrence of the bug.
> delete trailing period which breaks issue URL

- REQUIRE
- src/Gurobi.jl
- src/GurobiSolverInterface.jl
- src/grb_attrs.jl
- src/grb_common.jl
- test/lp_02.jl
- test/lp_04.jl
- test/qcqp_01.jl
- test/qp_01.jl
- test/qp_02.jl
Earliest Compat version is 0.18: https://github.com/JuliaLang/Compat.jl/commit/3866f8b9c43a9c5a4b99bb2f6133340eaa1bbce7
Passes tests on 0.6 and 0.5.
> Fix deprecation

- src/GurobiSolverInterface.jl
- src/grb_common.jl
- src/grb_vars.jl
- test/large_coefficients.jl
- test/runtests.jl
As [stated by Gurobi](https://groups.google.com/forum/#!topic/gurobi/M_Bzc6RWMhU), "everything that is larger than 1e+100 is silently converted into 1e+100. For bounds, the value is actually 1e+30. So, every bound value that is larger than 1e+30 (smaller than -1e+30) is truncated to 1e+30 (-1e+30)."
This pull requests introduces a warning rather than silently failing. It is made slightly more complicated by the fact we have to propagate the truncation through the `m.obj` vector we keep around to verify Gurobi stores the correct objective.
Closes https://github.com/JuliaOpt/Gurobi.jl/issues/94.
> Add warnings when using large coefficients

- src/GurobiSolverInterface.jl
Gurobi ([since at least v6.0](http://www.gurobi.com/documentation/6.0/refman/optimization_status_codes.html#sec:StatusCodes)) has returned a `CUTOFF` status code. 
This is correctly processed in [`grb_solve.jl`](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_solve.jl#L28-L60), but is not recognized as a solution status in [`GurobiSolverInterface.jl`](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/GurobiSolverInterface.jl#L420-L446). 
This results in a spurious error (as shown in the logs below) when the user passes a solver with a cutoff option `GurobiSolver(Cutoff = 10)`. An example (partial) log is shown below.
```
...
Root relaxation: objective 0.000000e+00, 243 iterations, 0.01 seconds
Nodes    |    Current Node    |     Objective Bounds      |     Work
Expl Unexpl | …
```
> Process cutoff status from inner model.

- src/grb_attrs.jl
- test/test_grb_attrs.jl
Allocating an entire `Array` is quite expensive and not actually necessary just to be able to pass a reference to a C function. Using a `Ref` saves 80 bytes of memory on Julia v0.6.3, and I think Julia v0.7 should be able to eliminate the memory allocation entirely. 
Before: 
```julia
julia> @btime Gurobi.get_intattr_old(m, $("NumQNZs"))
80.248 ns (1 allocation: 96 bytes)
0
```
After: 
```julia
julia> @btime Gurobi.get_intattr(m, $("NumQNZs"))
70.103 ns (1 allocation: 16 bytes)
0
```
> use Ref instead of Array when getting Gurobi parameters

- src/grb_common.jl
- src/grb_constrs.jl
- test/MathProgBase/large_coefficients.jl
- test/constraint_modification.jl
- test/runtests.jl
`chg_coeffs` when called with scalar indices was previously allocating a length-1 vector of indices and values, which is pretty inefficient. This PR changes that to using Refs, which are quite a bit cheaper. `getcoeff` was also unnecessarily allocating a vector for its return type, so I changed that as well. I deprecated the `getcoeff!` method which operated on that unnecessary vector. 
I also added some unit tests to verify the basics of getting and setting coefficients. 
Setting a single coefficient goes from `214.000 ns (5 allocations: 480 bytes)` to `89.000 ns (3 allocations: 48 bytes)` after this PR. Performance should improve even more in v0.7, since the Refs won't need to be heap-allocated. 
I also fixed some remaining deprecation warnings in the MPB tests. 
@odow this is a PR …
> Improve performance of coefficient modification

- src/MOIWrapper.jl
- test/MOIWrapper.jl
Fixes #111 (for the MOI interface). Requires https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/44
This currently contains a really gross workaround for the issues discussed in https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/44#issuecomment-409373755 . I'm happy to wait until we have a better solution for that before merging; I just wanted to get this PR opened so I won't forget about the changes.
> Pass constant objective terms all the way to the solver

- src/MPBWrapper.jl
this seemed to fix an issue I was encountering with some Pajarito models on Julia 0.6.4
> fix missing "numvar" method during MIPNode heuristic callback

- src/MOIWrapper.jl
Best reviewed commit-wise.
<s>
The first commit changes the process for changing variable bounds from one that made a few vectors, looped through data <s>twice</s>thrice, and then made two C calls, to a simple loop that sets the bounds element-wise. For small numbers of variables (e.g., changing the bound of a single variable), this PR comes out ahead. For moderate numbers (e.g, 10 variables), it is ~5% slower, and then for large numbers (e.g., > 100) it's back in front. I must have tested on different LQOI commits. Here are the latest benchmarks:
```julia
using Gurobi, BenchmarkTools
const MOI = Gurobi.MOI
function setup(N)
model = Gurobi.Optimizer()
x = MOI.add_variables(model, N)
c = MOI.add_constraints(model, MOI.SingleVariable.(x), Ref(MOI.EqualTo(1.0)))
return model, c
end
function …
```
> Style and performance improvements

- src/MOIWrapper.jl
It seems like something must have changed going from v7.0.x to v7.5.x because Gurobi no longer throws an error querying 0 elements.
> Fix ray queries for Gurobi 8

- README.md
- deps/build.jl
I think this would be useful for CI testing of packages for which a subset of the tests require Gurobi. For such packages, it would be nice to be able to put tests that depend on Gurobi in an`if haskey(ENV, "CI") ... end` block.
On a machine with a Gurobi license, Gurobi needs to be a test dependency, so it should be in the `REQUIRE`/`Project.toml` file. But on CI, testing currently errors because Gurobi cannot be built due to the `!found` check, even though Gurobi would not actually be used at test time. Setting the `GUROBI_JL_SKIP_LIB_CHECK` variable on CI could then be used to make Gurobi installable.
I can add a note to the readme if you're OK with this change.
> Introduce GUROBI_JL_SKIP_LIB_CHECK environment variable.

- src/MOI_wrapper.jl
Closes #168
@joaquimg until JuMP outputs nicely vectorized code, we should be overloading the singular `set_variable_bound` instead of just `change_variable_bounds!`.
```julia
using Gurobi, BenchmarkTools
const gurobi_env = Gurobi.Env()
const LQOI = Gurobi.LQOI
function benchmark_3a(model, x)
for i in 1:length(x)
LQOI.set_variable_bound(model, MOI.SingleVariable(x[i]), MOI.GreaterThan(1.0 * i))
end
Gurobi.update_model!(model.inner)
end
function benchmark_3b(model, x)
for i in 1:length(x)
MOI.add_constraint(
model, MOI.SingleVariable(x[i]), MOI.GreaterThan(1.0 * i))
end
Gurobi.update_model!(model.inner)
end
function benchmark_3c(model, x)
MOI.add_constraints(
model,
MOI.SingleVariable.(x),
[MOI.GreaterThan(1.0 * i) for i in 1:length(x)]
)
Gurobi.update_model!(model.inner)
end
function …
```
> Improve setting of variable bounds

- README.md
- deps/build.jl
See the discussion: https://github.com/JuliaOpt/Gurobi.jl/issues/195#issuecomment-465160480
Gurobi 7.0 is the earliest version with documentation on the Gurobi website. 
Versions prior to v7 have different default behaviour with the `UpdateMode` parameter and so do not work with the MOI wrapper.
> Remove support for Gurobi < v7.0

- src/MOI_wrapper.jl
- src/grb_constrs.jl
- src/grb_model.jl
- src/grb_quad.jl
- src/grb_solve.jl
- test/MOI_wrapper.jl
Following https://github.com/JuliaOpt/JuMP.jl/issues/1035: implement IIS support in a third package. 
The low-level part was already done here, so I just added the MOI part (which required accessing the error code from the C API).
> Compute IIS

- deps/build.jl
This PR adds a common diagnostic to the Gurobi install. It tries to catch and inform the user about common errors.
Closes #221
> Add diagnostic to build.jl

- README.md
Remove some unnecessary fluff at the top of the README and move the JuMP usage to the top, with a link to the Gurobi parameters.
Closes #226
> Update README to move JuMP usage higher

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
There are a few todos:
In Gurobi.jl
In MathOptInterface.jl
> Add VectorOfVariables-in-SecondOrderCone

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Simplified (and corrected) handling of variable and constraint names. Note that instead of trying to maintain the name-to-X mapping, we just throw it away if anything changes. This is inefficient if your workflow is add-query-add-query-etc. But it should be fine for the most common work-flow of add a lot of things - query.
Fixes #249
> Fix handling of duplicate names

- src/MOI_wrapper.jl
Arised from a discussion with @odow and @mlubin.
MOI.delete already has a fallback method for a vector of variable parameters (which just calls the single variable delete over each variable of the vector). The problem is that this fallback has O(n^2) performance the way the things are now (i.e., needing to update the model after each single variable deletion to keep the correspondence between MOI indexes and internal gurobi indexes). This specialization fixes the problem in an easy way but limited way (a better but much more complicated solution would be restructuring the whole lazy update implementation to keep a map between MOI indexes and internal Gurobi indexes).
> Specialization of MOI.delete for vector of variables 

- src/grb_env.jl
- test/C/test_grb_params.jl
One test fails but it seems unrelated:
```
solve_const_scalar_objective: Test Failed at /home/blegat/.julia/dev/MathOptInterface/src/Test/UnitTests/unit_tests.jl:64
Expression: ≈(MOI.get(model, MOI.ObjectiveValue()), objective_value, atol=atol, rtol=rtol)
Evaluated: 3.0 ≈ 4.0 (atol=1.0e-8, rtol=1.0e-8)
Stacktrace:
[1] #test_model_solution#12(::Float64, ::Array{Tuple{MathOptInterface.VariableIndex,Float64},1}, ::Nothing, ::Nothing, ::typeof(MathOptInterface.Test.test_model_solution), ::MathOptInterface.Bridges.LazyBridgeOptimizer{Gurobi.Optimizer}, ::MathOptInterface.Test.TestConfig{Float64}) at /home/blegat/.julia/dev/MathOptInterface/src/Test/UnitTests/unit_tests.jl:64
[2] (::MathOptInterface.Test.var"#kw##test_model_solution")(::NamedTuple{(:objective_value, …
```
> Fix GurobiError with unknown params

- README.md
As discussed with @odow in https://github.com/JuliaOpt/Gurobi.jl/pull/300, this updates the documentation of README.md to give new JuMP.jl+Gurobi.jl users a warning about the most common performance pitfall (so they may be already aware of it and structure their JuMP programs accordingly). This will also probably help users that find the "excessive updates" message and search for how to fix it.
> Adds section Common Performance Pitfall with JuMP.

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
The first commit adds a test uncovering a bug in SOC constraints. The bug was that defining a negative lower bound on the `t` variable of a SOC constraint by means of `add_constraints` (batch version) silently corrupted the related `VariableInfo` object, but using `add_constraint` (single-variable version) worked.
The second commit solves the bug by reworking many methods to work correctly with batch/vector (that is where the bug appeared) and changing single-element methods to wrap arguments and call the batch/vector variant. This way there will exist no difference in behavior between single-element and batch methods.
I know it is rude to ping specific people to review (specially in these times of Covid19), but if  @odow could review it quickly, I can send a PR tomorrow for the caching …
> Fix bug in setting a negative lower bound of a SOC constrained variable with `add_constraints`

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
I have only did it for MOI.ScalarAffineFunction constraints. This is merely a performance improvement. JuMP and MathOptInterface already have batch constraint deletion fallbacks and they will correctly call this method when it is the case. I did not add new tests nor benchmarks, but did call `JuMP.delete` in my code (that had performance problems), checked if the method was really called (with a `println` already removed), and the performance difference was from 23.2 seconds to 0.531 seconds (~29k constraints deleted from ~36k constraints, the speedup was probably higher than the ~43x because I am timing two batch variable deletions in these measurements, instead of just the constraint deletion, and they did not change performance with the changes introduced by this commit).
I executed …
> Adds a specialization of MOI.delete that deletes a batch of constraints.

- src/MOI_callbacks.jl
- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Gurobi.Optimizer now have fields `next_column` and `columns_deleted_since_last_update`. The behavior now is to not force a update before deleting, but instead: update the list of variables in Julia side but not their column indexes, and save the column indexes of the ones deleted; when updating the model then update the column indexes in Julia side.
The code pass all tests. But maybe we need to devise new ones.
This fix #315 in my code (that unfortunately is not a MWE).
I will be out for about 2 hours now, @odow, after this I will check if you have suggested something to me to improve in this PR.
> Adds buffering for variables deleted.

- src/grb_params.jl
Resolves issue #327 regarding parameters in Gurobi 9.0 not being included in the grb_params.jl file.
> Update Gurobi parameters to include new params released in 9.0

- src/MOI_wrapper.jl
Added comment asked by @blegat. Fixed comment on the negativity/positivity of reduced costs. Added a global const union for a common union. Changed the linebreaks of many comments in an effort to keep them close to 80 characters. Other minor changes.
> Comments overhaul

- Project.toml
- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
JuliaOpt/MathOptInterface.jl#1056 is merged and will be included in the next MOI release.
Several return codes are not yet in MOI, though. Should they be included in MOI?
> Update IIS support to MOI 0.9.14.

- src/Gurobi.jl
- src/MOI_indicator_constraint.jl
- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Add indicator constraint support

- src/MOI_callbacks.jl
- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Closes #52
Closes #53
An updated attempt at #52, inspired by #53.
Does anyone watching this repository have access to a Windows machine they could test this on?
Throwing an interrupt from a callback worked, but on Mac, I could not get a script to exit correctly on CTRL+C. I have to hold down CTRL+C to force a SIGINT, and then I get a Gurobi Error 10017, `OPTIMIZATION_IN_PROGRESS`.
```julia
ERROR: Gurobi Error 10017: 
Stacktrace:
[1] _check_ret at /Users/oscar/.julia/dev/Gurobi/src/MOI_wrapper.jl:266 [inlined]
[2] _get_intattr(::Gurobi.Optimizer, ::String) at /Users/oscar/.julia/dev/Gurobi/src/MOI_wrapper.jl:2398
[3] _is_mip at /Users/oscar/.julia/dev/Gurobi/src/MOI_wrapper.jl:2429 [inlined]
[4] get(::Gurobi.Optimizer, ::MathOptInterface.DualStatus) at …
```
> Catch [CTRL+C] and gracefully exit

- Project.toml
- deps/build.jl
- src/Gurobi.jl
x-ref: https://github.com/JuliaRegistries/RegistryCI.jl/issues/283
> Add checks for RegistryCI AutoMerge

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Add farkas dual for variable bounds

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
I've added two methods to ``MOI.set`` that allow you to set variable/constraint basis status. This is surprisingly difficult behavior to test: I don't think it's possible to check the basis status in Gurobi without optimizing the model, at which point you can only indirectly measure if your basis was correctly set.
I also looked at adding tests at the MOI level, but it got complicated when I tried to figure out how to make this work with universal fallback, so I punted.
> MOI.set for basis status

- src/MOI_wrapper.jl
Before, `Optimizer.variable_info::CleverDicts.CleverDict{MOI.VariableIndex,_VariableInfo}` was not a concrete type since the last two type parameters (for the hash and reverse_hash functions) were omitted. This lead to type instability, most notably for me in `_update_if_necessary`. Here's a pprof snippet from a larger program that solves a number of relatively easy LPs:
This change 1) specifies a concrete type for `variable_info` and 2) changes the constructor called to make this work. The hash/reverse hash functions are identical to what would be used anyway by the originally used constructor.
Pprof after the change:
> Make Optimizer.variable_info field a concrete type

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
While doing some benchmarking, I noticed that calling `MOI.add_constrained_variable(::Gurobi.Optimizer, set::Gurobi._SCALAR_SET)` was spending roughly the same amount of time in `GRBaddvar` as it was in setting the bound attributes. This seemed a bit wasteful, so I added a new method that lives here that sets the bounds directly in `GRBaddvar`.
I'm a bit uncertain how to update `lower_bound_if_bounded` and `upper_bound_if_bounded`. The comments for `_VariableInfo` suggest that these fields should be NaN if and only if a variable has no bound constraints on it. That will never be the case in this method, so therefore I should set both bound values, even to +/-Inf for one-sided bounds. However, after looking through the rest of the file I'm not certain that this is the behavior actually …
> Add method to MOI.add_constrained_variable

- Project.toml
- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Solves JuMP roadmap item "Accessing multiple results from solvers."
Here's what the test looks like at the JuMP level:
```Julia
using JuMP, Gurobi, Random, Test
function _is_binary(x; atol = 1e-6)
return isapprox(x, 0; atol = atol) || isapprox(x, 1; atol = atol)
end
N = 30
Random.seed!(1)
item_weights, item_values = rand(N), rand(N)
model = Model(Gurobi.Optimizer)
@variable(model, x[1:N], Bin, start = 0)
@constraint(model, item_weights' * x <= 10)
@objective(model, Max, item_values' * x)
optimize!(model)
RC = result_count(model)
@test RC > 1
for n in [0, RC + 1]
@test_throws MOI.ResultIndexBoundsError value.(x; result = n)
@test_throws MOI.ResultIndexBoundsError objective_value(model; result = n)
end
for n = 1:RC
xn = value.(x; result = n)
@test all(_is_binary, xn)
@test isapprox( …
```
> [MOI] Allow accessing multiple results

- Project.toml
- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
`PrimalStatus` always returned `NO_SOLUTION` if `.N != 1`.
> Fix handling of solution statuses for multiple results

- src/MOI_wrapper.jl
This PR intends to solve #397. The PR creates a generic mechanism that allows Gurobi Error Codes  to interpreted as termination status by the Gurobi wrapper. For now, it is used only for transforming `OUT_OF_MEMORY` in `MOI.MEMORY_LIMIT`, but new conversions only need to add a new element to a global internal Dict. The mechanism consist in one extra field for `Gurobi.Optimizer` (called `fake_termination_status`), a new internal function `_check_ret_GRBoptimize`, a new internal global `_FAKE_TERMINATION_STATUS`, and changes to `_raw_status`, `Optimizer` (constructor), `is_empty`, `empty!`, and `optimize!`.
The code is well commented. I did not add tests. If tests are deemed necessary, then I would like that someone more familiar with exception testing inside `Gurobi.jl` gave me some …
> Add fake termination status to Gurobi (so it become compliant with MOI.MEMORY_LIMIT)

- src/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Fixes an issue similar to https://github.com/jump-dev/CPLEX.jl/issues/365.
Mostly a copy-paste from https://github.com/jump-dev/CPLEX.jl/pull/367.
> Allow retrieving conflict status for integrality constraints.

- test/MOI/MOI_wrapper.jl
This ensures that an issue like https://github.com/jump-dev/CPLEX.jl/pull/366/files doesn't sneak in.
Another solution may be to move some IIS tests to MOIT, but I don't know how to test `Gurobi.ConflictStatus` (or the CPLEX equivalent) in that case.
> Explicit tests for MOI.TerminationStatus with infeasible statuses

- deps/build.jl
This should avoid issues like #387 (as it recently popped up in Gitter).
> Error message when installing Gurobi.jl on 32-bit Julia.

- src/MOI_wrapper/MOI_wrapper.jl
This crops up all the time: https://discourse.julialang.org/t/gurobi-license-issue/36547/8
I had just assumed the text of the error was coming from Gurobi, not us.
Closes #417
> Improve error handling of license problems

- Project.toml
- src/MOI_wrapper/MOI_callbacks.jl
- src/MOI_wrapper/MOI_indicator_constraint.jl
- src/MOI_wrapper/MOI_multi_objective.jl
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_callbacks.jl
- test/MOI/MOI_multiobjective.jl
- test/MOI/MOI_wrapper.jl
- test/runtests.jl
> Breaking changes for MOI 0.10.0

- src/MOI_wrapper/MOI_callbacks.jl
- test/MOI/MOI_callbacks.jl
Executes the lazy constraints callback (if defined) when where=MIPNODE so that the callback is executed at fractional values. Added a test using callback_knapsack_model to ensure some fractional solutions reach the callback in this example.
Note: branched this from v0.9.14 as v0.10.0 forces a downgrade to JuMP 0.18
> Run the lazy constraints callback at MIPNODE

- .github/workflows/ci.yml
- Artifacts.toml
- Project.toml
- deps/build.jl
- src/Gurobi.jl
- src/MOI_wrapper/MOI_wrapper.jl
No idea if this will work, but let's see.
cc @simonbowly
> Add continuous integration

- README.md
This now matches the verbiage in CPLEX.jl:
> Thank Gurobi in README

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
I applied the same tricks used in Xpress.jl here to fix 3 failed MOI tests.
The `test_solve_conflict_feasible` fails because Gurobi cannot compute IIS on a feasible model
> Fix failed MOI tests

- Artifacts.toml
- src/Gurobi.jl
The script to update the hashes is
```Julia
run(`wget https://packages.gurobi.com/9.5/gurobi9.5.0_linux64.tar.gz`)
using Tar, Inflate, SHA
filename = "gurobi9.5.0_linux64.tar.gz"
println("sha256: ", bytes2hex(open(sha256, filename)))
println("git-tree-sha1: ", Tar.tree_hash(IOBuffer(inflate_gzip(filename))))
```
> Update to Gurobi 9.5

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_callbacks.jl
- test/MOI/MOI_wrapper.jl
replaces #447 (CI would not run on PR from fork)
fixes #395
> fix error due to adding null callback

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Fix GRBgetstrparam

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_callbacks.jl
- test/MOI/MOI_multiobjective.jl
- test/MOI/MOI_wrapper.jl
- test/runtests.jl
> Silence test outputs

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
This is a follow-up from https://github.com/jump-dev/MathOptInterface.jl/pull/1800
It significantly improved the performance of updates. Using the same code from the PR above:
```julia
julia> @btime update_parameters_multiple_times_with_single_change(num_variables, num_solves)
18.970 ms (55878 allocations: 7.52 MiB)
julia> @btime update_parameters_multiple_times_with_multiple_changes(num_variables, num_solves)
6.163 ms (5786 allocations: 2.64 MiB)
```
> Add MOI.modify for multiple changes at once

- src/MOI_wrapper/MOI_wrapper.jl
As described in #473, it would be nice to create Gurobi environments that specify a Gurobi remote server. This is my first attempt to ir. Tested locally with a docker Gurobi server.
It amounts to:
- Modify the default Env constructor to allow it to create an unstarted environment (controlled by a kw argument in order not to break functionality).
- Add a function createRemoteEnv that sets the corresponding parameters in the low level C object.
- Optionally, start the environment. This starts the connection to the server.
Optionally this could be done by setting an appropriate gurobi.lic that loads directly the parameters ComputeServer and ServerPassword, but this is cumbersome when you have multiple servers or locally installed licenses, so I think this may be useful functionality.
> Added remote environment capability

- Artifacts.toml
I don't know why the artifact is downloaded on Windows: https://github.com/jump-dev/Gurobi.jl/issues/479
Maybe this will help.
Closes #479
> Lazily download artifact

- Project.toml
- src/Gurobi.jl
Using the stdlib is preferred over `Pkg.Artifacts`.
> Switch to LazyArtifacts

- Project.toml
- src/MOI_wrapper/MOI_wrapper.jl
I went for the easy way: fall back to the `RawOptimizerAttribute`
___
EDIT: I have updated the PR to follow the conclusions of https://github.com/jump-dev/MathOptInterface.jl/issues/1936
At the moment, the present branch only works with `MOI#master`
> Add support for Absolute/Relative gap tolerances

- Artifacts.toml
- src/Gurobi.jl
```julia
run(`wget https://packages.gurobi.com/10.0/gurobi10.0.0_linux64.tar.gz`)
using Tar, Inflate, SHA
filename = "gurobi10.0.0_linux64.tar.gz"
println("sha256: ", bytes2hex(open(sha256, filename)))
println("git-tree-sha1: ", Tar.tree_hash(IOBuffer(inflate_gzip(filename))))
```
> Bump binaries to v10.0.0

- src/MOI_wrapper/MOI_callbacks.jl
- test/MOI/MOI_callbacks.jl
Closes #494
@votroto is this what you were after?
> Change heuristic callback status to UNKNOWN instead of REJECTED

- Project.toml
- src/MOI_wrapper/MOI_multi_objective.jl
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_multiobjective.jl
- test/runtests.jl
x-ref: https://github.com/jump-dev/MathOptInterface.jl/pull/2070
x-ref: https://github.com/jump-dev/JuMP.jl/issues/2099
x-ref: https://github.com/jump-dev/JuMP.jl/pull/3176
> Add support for vector-valued objective functions

- src/MOI_wrapper/MOI_multi_objective.jl
> Add MultiObjectiveAttribute for interacting with multiobjective attributes

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Fix infeasibility certificate tests

- Project.toml
For most users this should be non-breaking. 
The only breakage is https://github.com/jump-dev/Gurobi.jl/pull/497, in which querying `ObjectiveValue` of a multi-objective optimization problem now returns a vector instead of the objective value of the first scalar objective.
This also has a minimal impact on the Pkg ecosystem because there is only one package with a dependency: https://juliahub.com/ui/Packages/Gurobi/do9v6/0.11.5 (cc @JoshKImperial for https://github.com/infrasenselabs/RoundAndSwap.jl)
> Prep for v1.0.0

- Project.toml
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Closes #514
The lazy update thing is really annoying. Most of the time it caches modifications in a queue, but it looks like deletions are handled separately to modifications.
> Fix bug modifying a constraint after deletion

- Project.toml
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
x-ref https://discourse.julialang.org/t/multi-objective-minlp-problem-in-jump/103117
> Fix support for MOI.TimeLimitSec

- README.md
This question came up at INFORMS, and it has been asked multiple times on discourse.
> Clarify Env module constants in README

- README.md
- src/MOI_wrapper/MOI_indicator_constraint.jl
- src/MOI_wrapper/MOI_wrapper.jl
> Add c_column and documentation for the C API

- README.md
We've had quite a few questions along these lines recently.
> Add C API from JuMP to README

- src/MOI_wrapper/MOI_indicator_constraint.jl
- test/MOI/MOI_wrapper.jl
> Fix deleting multiple indicator constraints in MOI wrapper

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Closes #546 
This is one option, but I don't really like it, because it relies on magic constants. Is there a way for Gurobi to tell us whether the problem is feasible according to any parameters the user has set?
> Check feasibility of solutions in PrimalStatus and DualStatus

- src/MOI_wrapper/MOI_callbacks.jl
- src/MOI_wrapper/MOI_indicator_constraint.jl
- src/MOI_wrapper/MOI_multi_objective.jl
- src/MOI_wrapper/MOI_wrapper.jl
Motivated by the large performance difference in [Discourse: Problem with JuMP + Gurobi.jl](https://discourse.julialang.org/t/problem-with-jump-gurobi-jl/111505). 
The idea is to only call `GRBupdatemodel` before `GRBget*` only. I've tried to adhere to calling `_update_if_required` at the start of the function or at the end. Additionally, adding the `force` argument to this function avoids having to use `_require_update`.
Some tests are failing still:
Work for the update part of https://github.com/jump-dev/Gurobi.jl/issues/516
> Refactor GRBupdatemodel calls

- src/MOI_wrapper/MOI_wrapper.jl
Closes #558 
No more `excessive time` warning:
```Julia
julia> m = read_from_file("/Users/oscar/Downloads/chainsing-10000-1.cbf.gz");
julia> set_optimizer(m, Gurobi.Optimizer)
julia> optimize!(m)
Gurobi Optimizer version 11.0.1 build v11.0.1rc0 (mac64[x86] - Darwin 22.6.0 22G630)
CPU model: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 99982 rows, 129976 columns and 239954 nonzeros
Model fingerprint: 0x2b705791
Model has 29994 quadratic constraints
Coefficient statistics:
Matrix range     [7e-01, 1e+01]
QMatrix range    [1e+00, 1e+00]
Objective range  [1e+00, 1e+00]
Bounds range     [0e+00, 0e+00]
RHS range        [1e-01, 1e+00]
Presolve removed 39994 rows and 29994 columns
Presolve time: 0.20s …
```
> Fix performance of adding SecondOrderCone constraints

- .github/workflows/ci.yml
- Artifacts.toml
- Project.toml
- README.md
- deps/build.jl
- src/Gurobi.jl
See https://github.com/jump-dev/Gurobi_jll.jl
There are still a few unresolved issues:
A potential first-pass is to use the binaries only on CI (or linux, to maintain compat).
Would fix issues like 
https://discourse.julialang.org/t/how-to-use-gurobi-11-in-julia-launched-by-anaconda/111271/2
Closes #509
> Use Gurobi_jll for binaries

- src/MOI_wrapper/MOI_wrapper.jl
```julia
julia> begin
model = read_from_file("benchmark/stroemer.mps.gz")
set_optimizer(model, Gurobi.Optimizer)
set_silent(model)
optimize!(model)
solution_summary(model)
end
* Solver : Gurobi
* Status
Result count       : 1
Termination status : OPTIMAL
Message from the solver:
"Model was solved to optimality (subject to tolerances), and an optimal solution is available."
* Candidate solution (result #1)
Primal status      : FEASIBLE_POINT
Dual status        : FEASIBLE_POINT
Objective value    : 2.77048e+05
Objective bound    : 2.77048e+05
Dual objective value : 2.77048e+05
* Work counters
Solve time (sec)   : 2.98400e-02
Barrier iterations : 0
Node count         : 0
julia> simplex_iterations(model)
ERROR: TypeError: in typeassert, expected Int64, got a value of type Float64
Stacktrace: …
```
> Fix return type of SimplexIterations

- Project.toml
- src/MOI_wrapper/MOI_wrapper.jl
> Add support for MOI.SolutionLimit

- src/MOI_wrapper/MOI_callbacks.jl
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_callbacks.jl
> Fix callback attributes in MOI.ListOfModelAttributesSet

- src/MOI_wrapper/MOI_nonlinear.jl
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
Alternative to #587: instead of filtering out the NL resultant variables when querying through MOI, don't add these variables to MOI at all so they don't show up in model queries.
- On deletion of NL constraints, deleted resvar indices are tracked on the deleted list for the next update operation
- In `_update_if_necessary`, the same index tracking trick applied to each entry in model.variable_info is applied to NL constraints as well, so that their resvar indices are appropriately adjusted following deletion of another variable.
> Track nonlinear resultant vars outside of MOI

- README.md
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
> Add Env(params::Dict) for setting parameters before GRBstartenv

- README.md
> Clarify how versions of Gurobi_jll are installed in README

- src/MOI_wrapper/MOI_callbacks.jl
- src/MOI_wrapper/MOI_wrapper.jl
Closes https://github.com/jump-dev/Gurobi.jl/issues/620
I tried a bunch of different approaches. This seemed like the most robust.
> Improve handling of SIGINT interrupts

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
x-ref https://discourse.julialang.org/t/gurobi12-reports-unbounded-to-a-nonconvex-qp-which-is-actually-bounded/126657/7
> Fix PrimalStatus when multiple solutions are available in DUAL_INFEASIBLE

- test/MOI/MOI_wrapper.jl
The previous example is only unbounded because of a bug in Gurobi
> Follow-up to #623 to use an actually unbounded model

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI/MOI_wrapper.jl
See https://discourse.julialang.org/t/about-jump-is-solved-and-feasible/126868
> Throw GetAttributeNotAllowed when ObjBound is GRB_INFINITY

- src/MOI_wrapper/MOI_wrapper.jl
@blegat: I'm not really sure what we originally intended here.
```julia
help?> MOI.DualObjectiveValue
DualObjectiveValue(result_index::Int = 1)
A model attribute for the value of the objective function of the dual problem for the result_indexth dual result.
If the solver does not have a dual value for the objective because the result_index is beyond the available solutions (whose number is indicated by the ResultCount attribute), getting this attribute
must throw a ResultIndexBoundsError. Otherwise, if the result is unavailable for another reason (for instance, only a primal solution is available), the result is undefined. Users should first check
DualStatus before accessing the DualObjectiveValue attribute.
See ResultCount for information on how the results are ordered.
```
> Change DualObjectiveValue to use Utilities.get_fallback

- src/MOI_wrapper/MOI_callbacks.jl
- test/MOI/MOI_callbacks.jl
Fixes https://discourse.julialang.org/t/memory-corruption-error-in-julia-incorrect-checksum-for-freed-object-when-running-a-jump-gurobi-model/130522
Nonlinear expressions introduce "hidden" variables, so the vector we were allocating for the callback solution was not long enough, and we were overwriting our memory space.
> Fix callback with MINLP and hidden variables

- README.md
Someone reached out to say they got confused by the instructions.
The first thing we should do is tell people to run `Pkg.add("Gurobi")`. All else follows.
> Clarify installation instructions in the README
